language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then mvn deploy --settings maven_deploy_settings.xml;
  else echo 'Pull request, skipping deploy.'; fi
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: h3dDuUqWW2HEnMxLf8B4VY8Jf2iiJianlsi9kxAZBmwY9LJgpUCzKcLQKYC2TAnIAWg6A9TGuchdXJjA5uWlxjdbqbhfK0VLRmwkk/CPXzZaiRLCYtQqY3bj58+z1ES/Bh5Wptvwn8kR5O3ErIW2+PVUVphgG0DmT+paiPF8g4c1HTU1vOWvb/NEZ83PigLPGilTDbXLUXI7oq5a4m9QyVD0MgDQWJAOjsNl6Pe7V6GeYu1k1FWhWw6luWnudvfC3jRCJJJEQJo506Ds7XGpC4lNUQoiFnGjPyUwc5r+LYr3ATc1Rjx0HLLB2+GcTUl6VOlufclHV0PER30qJyX4aH9iqIPVxliu+VA6Mnt0Yw11nkxBRn4NZbKX4HXVDy3z/G+ScMgM9mK+wLJZ3NnVOn/jH904CAp8nZgjh1XzhaE6bBJ3jo4NQZrZI89wImb6oMzVkJwEO4HJLUEEol4X3gE6Pa5XiBVdOdYwAHg8f7WBqXHPHDESEb2YiaPk+vh0VtATILpNRfapBImJqv5+W+WetrOqvQxeVOVY1h4m0ZRIwucdSWgkakiTcr75KDPaRW9KJQVg5UrFKcek9OOylHuYXT7CSzTjPQ+D/K1dzEDZ+pMAvX0zPuKFCgOViUx5JMpIdWAwP4TEhTtLl4IQxwOVua//L/wmYceezTTfp20=
  - secure: WecmA21oSdRgz0w1s2FP0nUVoOxZdna8IxiC6bLoBLdydoLT4l/J+GySwV8nFdt5LtKRzhzaAUVpzhq7DKzpedVuAFg+EFMwH2W56VycZ3lBzL0n8NcELPBVgn9ROHM3VEeYk03JbY0MDl5W627JLMjVl0G5E8sln24PY1ACYnzDXb9aDcktLpqQsbF/0f8Gx+byWFR20e2+hsZw6FoVG/h1GgcbqU9HpUuU7IRfwPigWh7dK7YX4Zox1ZliPXpGj9QHtwJ3iTt4OT4gmnhKiITk2xaOK3tItNosVpusWWoQw/W1S5NS36KtZ0wPrkYr33OMzegiomKuHht4okFnjnw8LNCbsFA4V9nJLZ+nsZKlVGeHVZtGncQzXTkEct3mA6OeN7apByQ5dKTXRsb13Megb0dHoNZ7F6S61wGNxgsNNjStpylrAcyxlmYwWM1KI3prlQch9W8o4iyz7u9jMi2oq97vsg/EcR3LK7f6goQzFkkOHgyimHgnk2bZ5U940ZHuTd6Qbb0/UG3ynFUUfp4ukT5NV3SoaKKzo9FaMRJgIZMpE8u1QUffm6Y1g8nGOLZFQYMWRR+YlZt2/fnuwvuWe6jhMkvu2PBf2Sqn5tF0aAg3uM3M/4eDK/s0VUPtsY4m2C0e/ybJIx++u9GQxjqBheUm0nsA9yFYukm0CrM=
