language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then mvn deploy --settings maven_deploy_settings.xml;
  else echo 'Pull request, skipping deploy.'; fi
cache:
  directories:
  - $HOME/.m2
env:
  oss-username:
    secure: IjADFSW4ntDM5b4Jaoz7VrHfl2PTWz5s7st9k2or8Tpf6JnJTdtl7GnhqWZDDzvKs1mXIHkSZzVZcUGh/SUprdSqcbuvJzL3u7xtum7jDCv5lKmBVJptF4OPrpLNrmL4l0fHxyDvn+TwsP6Az+yIhJ1Wn8mxjMcxeFCDmuZ1JfWtMk3zTI5xU8i8x2K4IULsTk8TcJZO3kPak5r6NYR0UkUazh0ZwRUh7BcrnSel/5Ki7SjpYAPnZuFEUZzzFK+Dl+Ohcy4F/CF8aYSSSb777TksAPvMGJotf+T4eDtqUG4ER3GNJJXrpHtg8t9iWUy9UfaM/G0z79A3w4tpzbvrhAbrvd5iDuzk56KDjHjZNKhwweRI2C8ZO843pGwiOSpM1AOKRXzZHXE34peRcrlDwzozym3UNhtKlHGiyOeBSowYexO4ZjWnMhlfC6o5smm7J2xpf9+sFGN0absBjTgQMQPniMv9C/X/8YEpXD2Grc+Mc6q27qhe5jYf3/1bH2v+lNY/M3EHss5rXFW4gYVbrzrWperOwNy8nEvmpclJKaYqR28gLaKg0Ew+xJmQzK0Cxq5KEZSWImPIJAmQFahWVlsL0LjO1LO4f039ean6Aaa4tRNlaOZPv7n5u12zLSUySC9RXi5N2ksOhBdyEuFh3vnDG4RC60mCBjyrCmuv1yk=
  oss-passwd:
    secure: jU6qCnjx4ap2GSZFokVQpOOzNZXwG+hjNb5EziWkcB8xjJeTxizPj6XJc/VxDdOCFEihGTW3sriVSoTo28qExJnVG5StNjs3dkUHcmEpFhac4hhIY1eWxwsNOwZMCTnXSxNYAn2JMiS/S5h0gDhBId8yWC2KNQw7GEI8UyMryljkQHWRUqIBL764uPy/ur5RRDwOkHhl8LXl2ywETlGmt7BkU0ziAX8XzH8KLoWXXVSXYKLY4JBinldXs1wruy8WYJ2hEW5CxEi1/I0yMdGOqblNramEZTFS2uxYYD9G6/khdfjZPZqpUgjiZHlNtej92j9JD0jI6Tf4cKzeYgokla6EBpFqDOYZqNJ7e/znbbe+cLqoJtEVgQWz5ab0lqHoPwEp8d/xbV3mDPLA1sujWRHdRF6z9kVMhDms++rN14fo6mItmKc0Hz1ytn5JxDlnwo6Vp4zJm0kwV1V91+3AY+2N58TE8ZkTLR/BKx74Ag5o6r5Jt95uK47H+uwOWXN4VPpe8D0rut76MpP5mEXUQ70mimmIJFsAcBklOmwY2XpGisiD4x7gLG5qJyo/jbJHLYzVxj2mbUGcvztyiHtiYfDT13rG++08WkhW59qv9IEJ/3lr7ZnBpUwueynwnQbVuVINR1RqTME7sNRhj7rFwNXf7AKgtizZ9FKl/EwZ4oI=
