language: java
jdk:
- oraclejdk8
after_success:
- mvn cobertura:cobertura coveralls:report
- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then mvn deploy --settings maven_deploy_settings.xml;
  else echo 'Pull request, skipping deploy.'; fi
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: dei6m/aAXZ0tpvBrXI1LtQWDWb+8nXGbs6CiPOEwDpgFrZ1HVkjroVnHBv4RZZZi2n5bQun29dhf8zc4jO1doea0sVx+mhwpqGnA0uTRwUz5tmAMGXmXVTF0fh0nT2GU964Dvz1X8PBUd8Y3jzlpHhl6cZVwxzmKmObzXhOpP0Tlj0xzri3qjbCYsIGPomQvF6Tn5+hRGWC7+i2vsGDDHP64voFFciisxkCLFdneBrPI+qRHH5ZiOANnm92yq1TZY9DTx8VMiAxClOK+H4Qn4izAtT/rNXcPIVu7sKnyIvhkmWjrlFej3wpxRffs1I1y4o7xfsa7L6zasUpIgPN7eiqNnFEUCTI+O/uk5+1c71iPnh/04PtIwQHIBejXBPT/UeYH8UCGFsl6NWfzGAGqItyc/4HC4RzB/1TjVxqgS3l8BAs0XaAFspJzJcTKeMN5r0/0tbmyPu4xxZqbXCQuMUQmB/NYTRlfdZjJm/FxoY9Cg+WqO7P3V1sK9ct5TjDgJQK1cjJSo5iwlgfTp5cUvqhR30CoguBJ3bSej/Tbq2oOQaObvUme9ruJCJUBYfIsZF2/Z2P59QYCTamvvX4W+CXf76ZXaTgSAbWPMvK6/8DM46RDvGPunnjdjDh6q/LAdMyYshW9AtIZxhWy3rdVMDLW72gOhViCb2V2KwTG8Hs=
  - secure: u8mMWc1wFupDcJm6L8dyed3jaDPh2V58lqtd7mywzQDchGdl9n0vDbgC/aQuLjLdLnKbpmI5abnAJuNi1dtuKzqZ/2GWthmPdKjGg5eOvFVSR1aKdEbfXV6PCCz4cxjg/XkLGh8B4VI+5o4MTbogEcfkWh3aHHcfB56zIjaZy8/N+3cFdRc7BhyaOO9F1A8pa/l234M9hlC8VHWyQBBg2Ac841n4jMaciOP4d50oqJFfV+DeNNowMnOZ6u0pOy7Glb7Cvh8euW67VHdLLqd9rupF8194LLfa+FnxEBQxoZw5bCJNcyadFk5yWz7srvZyjFWshvkBkHi4Jgqf9YILMDNzYcZGeb3M+q7NPXHHWpwT8qicDTRERmLalowWIQeP56EMZ89Uaw3oUboPJX+gIeuYqjn27QeFnw6fYpqwq7CoHq1vk5Tt/pkMZq6BdpMnCc+OcDhoPa4TTvWt1fuQ8UHnru2T7Z6xUOyPFCUP3TReUzBXj4CBwT44o9xglSmQS/UanbfQNvUWN1JoJrSzVFl3WtGoHeoMknA8Usv6WkllDYk9wCcvHhcm33BgxyGC1usgCk5B+OaL9NhkV6HfxY6ThvLw5LWgOMNkJ01kfehVZG1bhckzZUfbyv721pqXz1JDJPiSNtjk26rFiCUeGkaB/ldADc9mcTtTBuNvp9o=
